extensions:
  myauthext:


receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
        auth:
          authenticator: myauthext
      http:
        endpoint: "0.0.0.0:4318"


exporters:
  debug:
    verbosity: detailed



service:
  extensions: [myauthext]
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [debug]
